apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::307946675108:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-pVATeICSVMOd
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::111122223333:user/kaveri
      username: kaveri
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-04T10:51:33Z"
  name: aws-auth
  namespace: kube-system
  uid: 48d38049-ceb3-49b4-b274-aa434f1332be