apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: expense-trainee
rules:
- apiGroups: [""] # "" indicates the core API group means v1, in v1 we which have pods, deployments, services, config maps like that all will coe under core api.
  resources: ["pods"] # she can only acces the pods
  verbs: ["get", "watch", "list"] # she have only read access for the pods
  # all this is a role we need to bind this to a user with rolebinding.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: expense-trainee
  namespace: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: expense-trainee
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: Kavya
